name: lint
on: workflow_call
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Cached Checkout
        uses: actions/download-artifact@v4
        with:
          name: pointd-checkout-${{ github.run_id }}

      - name: untar
        run: tar -xzf ../pointd-checkout-${{ github.run_id }}.tar.gz

      - name: lint
        run: npm run lint
