name: "Pull Request Labeler"

on:
  - pull_request

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Custom labels
        uses: actions/labeler@v5
        with:
          sync-labels: true

      - name: Assign size label
        uses: pascalgn/size-label-action@v0.5.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "XXS",
              "20": "XS",
              "50": "S",
              "100": "M",
              "400": "L",
              "1000": "XL",
              "2500": "XXL"
            }
