name: lint
on: workflow_call
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Cached Checkout
        uses: actions/download-artifact@v4
        with:
          name: pointd-checkout-${{ github.run_id }}

      - name: untar
        run: tar -xzf ./tar/pointd-checkout-${{ github.run_id }}.tar.gz

      - name: test
        run: npm run test
